version: "3.9"

services:
    mongodb:
        image: mongo:7.0
        container_name: useTeam-mongodb
        command: ["--replSet", "rs0", "--bind_ip_all"]
        ports:
            - "27017:27017"
        volumes:
            - ./docker/mongo/data:/data/db
        healthcheck:
            test: ["CMD-SHELL", "mongosh --quiet --eval 'db.adminCommand({ ping: 1 }).ok' || exit 1"]
            interval: 5s
            timeout: 2s
            retries: 30

    mongo-rs-init:
        image: mongo:7.0
        container_name: useTeam-mongo-rs-init
        depends_on:
            mongodb:
                condition: service_healthy
        entrypoint:
            - bash
            - -lc
            - |
                mongosh --host mongodb:27017 --eval '
                  const rsStatus = rs.status().ok;
                  if (!rsStatus) {
                    rs.initiate({_id:"rs0", members:[{_id:0, host:"mongodb:27017"}]});
                  }
                ' || true
        restart: "no"

volumes: {}
